kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook
  namespace: YOUR_NAMEYOUR_NAMEYOUR_NAMEkeysight-tudor
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: registry.k8s.io/guestbook:v3
        imagePullPolicy: Never
        ports:
        - name: http-server
          containerPort: 3000

---

kind: Service
apiVersion: v1
metadata:
  name: guestbook
  namespace: YOUR_NAMEYOUR_NAMEYOUR_NAMEkeysight-tudor
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
