kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-master
  namespace: 
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    app: redis
    role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis
        ports:
        - name: redis-server
          containerPort: 6379

---

kind: Service
apiVersion: v1
metadata:
  name: redis-master
  namespace: 
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master

---

kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-replica
  namespace: 
  labels:
    app: redis
    role: replica
spec:
  replicas: 2
  selector:
    app: redis
    role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
      - name: redis-replica
        image: registry.k8s.io/redis-slave:v2
        ports:
        - name: redis-server
          containerPort: 6379

---

kind: Service
apiVersion: v1
metadata:
  name: redis-replica
  namespace: 
  labels:
    app: redis
    role: replica
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: replica
